### ISSUE TITLE
Field level security message

### ISSUE THREAD

**Issue by CREFaulk** [MarkMpn/MarkMpn.SecurityDebugger#3]
This seems to be related to FLS and wasn't recognized.

User with ID 64708701-9323-eb11-811c-005056956b45 does not have Update permissions for the donotphone attribute in the lead entity. The leadid of the record is 9e5ec118-24a8-e911-8114-005056954a40

Thanks for the tool! It works great for role based and it really helps to show what the options are for correcting the issue.

**Comment by MarkMpn** [comment]
Thanks for these details, this type of error will be handled in the next update!

**Comment by CREFaulk** [comment]
Hi Mark, thanks for the update.
