### ISSUE TITLE
Message Not Recognized as Permissions Related

### ISSUE THREAD

**Issue by lcfuqua1** [MarkMpn/MarkMpn.SecurityDebugger#4]
Just letting you know that I was attempting to use the tool and received the notification that my error message was not recognized. 

Per the suggestion in the error message I am providing an attachment with the log file. 

Thank you for your work on this tool it is very beneficial. 
[ErrorDetails (2).txt](https://github.com/MarkMpn/MarkMpn.SecurityDebugger/files/7816767/ErrorDetails.2.txt)

**Comment by MarkMpn** [comment]
Thanks for these details, this will be fixed in the next update!
