### ISSUE TITLE
Message not interpreted when the error occurs for a record creation

### ISSUE THREAD

**Issue by MscrmTools** [MarkMpn/MarkMpn.SecurityDebugger#5]
Hi @MarkMpn,

I have found that if a user gets a security error message because he tries to create a record with a different owner, the tool does not find the record (which is normal because it does not exist) and stop interpretating the error.

It could be nice if the tool was able to indicates the problem when creating a record with another owner

Here is the error message:

Principal with id 9bc81194-9ebb-ea11-a812-000d3ab2a6be does not have CreateAccess right(s) for record with id 00000000-0000-0000-0000-000000000000 of entity incident. Details: {"CallerPrincipal":{"PrincipalId":"9bc81194-9ebb-ea11-a812-000d3ab2a6be","Type":8,"IsUserPrincipal":true},"OwnerPrincipal":{"PrincipalId":"5d957f62-9ebb-ea11-a812-000d3ab2a6be","Type":8,"IsUserPrincipal":true},"ObjectId":"00000000-0000-0000-0000-000000000000","ObjectTypeCode":112,"EntityName":"incident","ObjectBusinessUnitId":"0e7fb2ad-df4d-ec11-8c62-000d3aba6882","RightsToCheck":"CreateAccess","RoleAccessRights":"None","PoaAccessRights":"None","HsmAccessRights":"None","GrantedAccessRights":"None","Messages":["PrincipalHasOwnerPrincipalWithAtLeastBasicPrivilegeDepth = False","EntityUserGroupRights = None","MinimumPrivilegeDepthRequired = Local","SecLib::AccessCheckEx2 failed. Owner Data: roleCount=4, privilegeCount=1350, accessMode=0; Principal Data: roleCount=5, privilegeCount=1580, accessMode=0"],"EntityOwnershipTypeMask":1,"CallerInfo":{"IsSystemUser":false,"IsSupportUser":false,"IsAdministrator":false,"IsCustomizer":false,"IsDisabled":false,"IsIntegrationUser":false,"Teams":null,"Roles":null},"ReadOnlyState":"UserAndOrgFullAccess","IsHsmEnabled":false,"HsmInfo":null,"AccessOrigin":null}

**Comment by MarkMpn** [comment]
Thanks @MscrmTools, the next release will handle this error.

**Comment by MscrmTools** [comment]
Great! Thank you @MarkMpn
